infra/scoped/api-gateway.tf
infra/scoped/api-model.tf
infra/scoped/auth0-client.tf
infra/scoped/auth0-database.tf
infra/scoped/auth0-email.tf
infra/scoped/lambda.tf
models/create-user.json
models/update-user.json
packages/apps/api-authorizer/src/index.ts
packages/apps/api/src/app.ts
packages/apps/api/src/handlers/auth.ts
packages/apps/api/src/handlers/user.ts
packages/apps/api/src/models/user.ts
packages/apps/auth0-actions/src/get_user.js
packages/apps/auth0-actions/src/login.js
packages/shared/auth0-client/src/auth0.ts
packages/shared/auth0-client/src/index.ts
packages/shared/identity-common/src/index.ts
packages/shared/sierra-client/src/index.ts
packages/shared/sierra-client/src/patron.ts

Implements the `[POST] /users` API operation. This involves creation of a Patron record in Sierra and a corresponding Auth0 user, the two of which are linked together via their corresponding identifiers.

Implements backend API support for user creation

---

infra/scoped/auth0-client.tf
packages/apps/api/src/handlers/user.ts
packages/shared/identity-common/src/index.ts

This PR handles the 30 character password length constraint that is imposed by Sierra. To handle this, a password provided is truncated to 30 characters in length if the password is greater than 30 characters. Auth0 itself does not impose password length limitations, but all passwords are effectively truncated to 72 characters to comply with the underlying bcrypt algorithm.

Implement maximum password length management

---

packages/account-management/Dockerfile

Previously, we were copying an empty folder from the git repo into the final layer of the AMS image instead of the folder produced by the build with the generated schemas. This meant that any attempt to call the FE API endpoint to create the account was erroring due to the missing files.

Copy schemas from build layer of AMS image

---

packages/account-management/src/frontend/AccountManagement/PasswordForm.tsx
packages/account-management/src/frontend/Shared/PasswordInput.tsx

The validation logic here seems ok to me, but the UX isn't great as the new password validation happens before the user has started typing.
The logic behind showing that "not valid" message is quite fiddly, and I'd rather write some unit tests than fiddle with it any further. Installing and configuring a UI testing framework isn't a trivial piece of work, and it shouldn't hold up this ticket. This PR meets the requirements as defined.

Add Current Password verification field to Change Password form

---

infra/scoped/api-documentation/users/get-param-sort.json
models/user-list.json
models/user.json
packages/apps/api/src/models/user.ts
packages/apps/auth0-actions/src/enrich_patron_attributes.js
packages/shared/auth0-client/src/auth0.ts

- Patron data is now only released through a `/userinfo` call if the `patron:read` scope was provided when the access token was generated.
- `patronId` has been renamed to `userId` in API response models (these two are equivalent).
- Validating that Auth0 is providing the required data to build up API responses - this is usually indicative of a lack of scopes attached to the provided access token.
- Certain fields (`firstName`, `lastName`, `lastLoginDate` and `lastLoginIp`) are optional in Auth0. This is now reflected in the API documentation.

Minor fixes to UserInfo attribute release and data models

---

infra/scoped/parameters.tf
infra/scoped/variables.tf
infra/static/parameters.tf

This PR allows the user component of the email address used for outbound emails to be configured on a per-environment basis.

Updated infrastructure to allow separate email users for different environments

---

infra/scoped/elasticache.tf
infra/scoped/iam.tf
infra/scoped/lambda.tf
infra/scoped/parameters.tf
infra/scoped/security-groups.tf
infra/scoped/variables.tf
infra/scoped/vpc.tf
packages/apps/api-authorizer/package.json
packages/apps/api-authorizer/src/index.ts
yarn.lock

Auth0 imposes a limit of 5 requests per minute against the `/userinfo` endpoint for a given user ID. This presents a challenge, as our API Authorizer implementation depends on the `/userinfo` endpoint to check for access token validity and to retrieve the callers user information to identify them. This occurs on every call the API.
To avoid hitting this limit, this PR introduces a caching mechanism using AWS Elasticache's Redis implementation. When an access token is successful retrieved from the `Authorization: Bearer ...` header, the Redis cache is first checked using the access token as a key. If an entry is found, the value is the user profile data for the caller, and the access token is assumed to be valid.
If no entry is found, the `/userinfo` endpoint is queried to determine the …

Implements caching mechanism for '/userinfo' lookups in API Authorizer

---

.buildkite/Dockerfile
infra/scoped/auth0-email.tf
infra/scoped/lambda.tf
infra/scoped/output.tf
infra/scoped/parameters.tf
infra/scoped/secrets.tf
infra/static/output.tf
infra/static/provider.tf
packages/apps/api/package-lock.json
packages/apps/api/package.json
packages/apps/api/src/app.ts
packages/apps/api/src/utils/email.ts
yarn.lock

Prior to these changes, the API was configured to use SES for sending email and SES only. This alters that configuration to use SMTP instead, and the SMTP configuration parameters are now stored in AWS Parameter Store and AWS Secret Manager.
This allows both Auth0 email configuration and the API email configuration to both use SMTP, and both are configured from the same AWS Parameter Store and AWS Secret Manager values.

Implements fully configurable SMTP for both Auth0 and API

---

packages/shared/sierra-client/tests/sierra-client.test.ts

This is me kicking the tires on the tests – I looked in the Buildkite config to see how tests are run, and ran a couple locally.

Add a couple of tests for 404 response branches

---

.pre-commit-config.yaml
infra/scoped/auth0-tenant.tf

This is required whenever the the `password` token exchange is utilised, so that Auth0 knows which connection the provided credentials are to be tested against. We use when a user provides their current credentials prior to a sensitive operation taking place.
Also fixes the `.pre-commit-config.yaml` to update to the new format.

Sets the default connection in the Auth0 tenant via Terraform

---

infra/scoped/api-stage.tf

This PR disable the API Gateway's `v1` stage logging trace, preventing request bodies (and thus potentially sensitive data) from being logged in CloudWatch.

Disabling trace logging for API Gateway

---

infra/scoped/auth0-tenant.tf

As part of the Auth0 deployment, we depend on Auth0's [auth-deploy-cli](https://github.com/auth0/auth0-deploy-cli) tool. This queries the Auth0 API to fetch the current state of a tenant, then dumps that to files. We override / update those files during deployment, and they are then written back to Auth0.
The [auth-deploy-cli](https://github.com/auth0/auth0-deploy-cli) tool queries the Auth0 Management API [to fetch the current HTML customisations](https://github.com/auth0-extensions/auth0-source-control-extension-tools/blob/198e2febc123a133b05f89c6d681589c0926568c/src/auth0/handlers/pages.js#L102) for the three pages supported by the Legacy Experience. It queries the API and gets JSON response, and then uses [the names of the three pages (which are hardcoded in the tool) …

Fixing issue with Auth0 deployment pipeline

---

.buildkite/scripts/init-environment.sh
infra/scoped/.terraform.lock.hcl
infra/scoped/backend.tf
infra/scoped/provider.tf
infra/scoped/variables.tf
infra/static/backend.tf
infra/static/provider.tf

This brings the terraform backend and provider config into line with other Wellcome Collection repos: it refers to roles explicitly by ARN rather than using local profiles, and pushes environment config/overrides into CI. It also enables state locking for the S3 backend. Developers will still need to provide environment variables to the Auth0 provider.

Standardise terraform backend & provider roles

---

.pre-commit-config.yaml
infra/scoped/auth0-client.tf
infra/scoped/backend.tf
infra/scoped/run_terraform.sh

In order to run terraform without having to copy paste credentials from Auth0, this change pulls the buildkite credentials from secrets manager and applies those to the running environment.
This allows terraform to be run in CI or locally and simplifies the process of running terraform. Using this change removes the need to have a client for each user and to maintain that either in or out of terraform. 
This change does remove one part of the audit trail to see who (i.e. which client) has made changes in Auth0, but at present that is of dubious value.
**Note:** The values required to be set in SM/SSM have been manually set for _stage_ only currently, they will need to be added for _prod_ before merging. We could set those values from (buildkite client id/secret) if there is appetite to do …

Add terraform runner script

---

infra/scoped/locals.tf

This is already applied due to how much of a headache moving things between VPCs is with leftover ENIs etc. It was a no-op in the prod stack as intended.

Separate VPCs per environment

---

packages/apps/api-authorizer/tests/api-authorizer.test.ts

This change adds a test to cover the case where an invalid resource is requested, in order to provide a better picture of application behaviour.
Trying to discern why https://github.com/wellcomecollection/identity/pull/151 is not working I wanted to see this behaviour, so added a test to cover it.

Add tests for invalid resource in api-authorizer

---

packages/apps/auth0-actions/src/databaseScriptGlobals.d.ts
packages/apps/auth0-actions/src/get_user.ts
packages/apps/auth0-actions/src/login.ts

Auth0 gives us some error classes to communicate different error causes - this gives us control over the microcopy, and fixes the bug that incorrect credentials on a first login returned a "something went wrong" error.
The copy used here is OK for now - see [Slack discussion](https://wellcome.slack.com/archives/C294K7D5M/p1625133599118500)

Return a more informative error from the login scripts

---

.buildkite/pipeline.deploy-stage.yml
.buildkite/pipeline.yml

This causes cascading failure between pipelines (and double posting failures in Slack) - fixed by adding async to deployment steps (we also do this in wellcomecollection.org & catalogue-api repos).

Decouple build/deployment failures

---

infra/scoped/ecs_services.tf

Requests does not have APM Tracing unlike Items & Search - it should, this adds it.
This change adds the config to the ECS service, this should go out before: https://github.com/wellcomecollection/catalogue-api/pull/204
Note: this is applied (targeted to requests module).

Add APM config to requests API ECS service

---

.buildkite/pipeline.deploy.yml
.buildkite/scripts/init-environment.sh

Previously the mechanism to deploy to prod required entering details into a manual input step, when we moved to separate stage/prod deployment steps that gate was not removed resulting in all deployments going to stage due to incorrectly set defaults.
This change removes the last bits of the "manual input step" and ignores webhook/ui deployment types (the deployment step is always triggered from another pipeline, never webhook or UI).
This change will hopefully fix the failing smoke tests in prod caused by latest changes not being deployed.

Remove input field deployments

---

infra/scoped/ecs_services.tf
infra/scoped/locals.tf

For https://github.com/wellcomecollection/platform/issues/5255
This exposes the environment variable to the app – I'll do a separate patch to actually use the variable.

Add the user hold limit to the requests service

---

infra/scoped/api-gateway.tf
infra/scoped/ecs_services.tf
infra/scoped/locals.tf
infra/scoped/terraform.tf

This means we'll get alerts of API Gateway errors for the identity APIs, which we haven't had before.
Note that I've had to cherry-pick https://github.com/wellcomecollection/identity/pull/168 back in, I'm not sure what happened to it. 🤷‍♀️ 
Requires wellcomecollection/platform-infrastructure#232, part of wellcomecollection/platform#5245

Add Slack alarms for 5XX errors from API Gateway

---

infra/scoped/auth0-client.tf
infra/scoped/auth0-connection.tf
infra/scoped/parameters.tf
infra/scoped/secrets.tf

Removes the Auth0 client for the account admin system and the Azure connector, which it required.

Remove identity-admin leftovers

---

infra/scoped/auth0-client.tf
infra/scoped/auth0-connection.tf
infra/scoped/output.tf

This change configures an OpenAthens SAML IDP in Auth0.
For https://github.com/wellcomecollection/platform/issues/5120

Add OpenAthens SAML IDP client to Auth0

---

infra/scoped/auth0-client.tf
infra/scoped/secrets.tf

In order to enable the OpenAthens sign-in for e-resources we need to add the callback URL provided by them to our config.
This change does that and stores the value provided by the SAML connector config for "Assertion Consumer Service URL" in secrets manager (I don't think this necessarily must be secret, but erring on the side of caution).

Add OpenAthens callback URL to config

---

infra/modules/ecs_service/main.tf

Enabling the ECS deployment circuit breaker , turns on detection of repeated failed attempts to start tasks as part of an ECS deployment and will "cancel" a deployment if a particular threshold for failed tasks is met.
See: https://github.com/wellcomecollection/platform/issues/5306
Note: This is only applied in stage so far!

Update ECS service module to version with circuit breaker protection

---

universal_login/prompt/reset-password.json

Change forgotten password screen back link from 'Back to Account Management System' to 'Back to sign in'.

Change backToLoginLinkText for the reset password screen

---

universal_login/deploy.ts

When deploying to stage the build can sometimes fail because we exceed the [rate limit for the Auth0 API endpoint](https://auth0.com/docs/support/policies/rate-limit-policy/management-api-endpoint-rate-limits)
This stops that from happening

prevent us hitting the API rate limit

---

infra/scoped/api-integration.tf

The context added by the custom authorizer is automatically passed to the Lambda API, but needs manual intervention to work for HTTP proxy integrations

Include caller ID as a custom header on the requests api integration

---

infra/scoped/auth0-email.tf
infra/scoped/locals.tf
infra/scoped/secrets.tf

Restores the email config (not templates) that https://github.com/wellcomecollection/identity/pull/194 removed; did some `state rm`ing and `import`ing to sort the rest out
(already applied)

Un-drift terraform

---

universal_login/emails/blocked_account.json
universal_login/emails/reset_email.json
universal_login/emails/verify_email.json
universal_login/emails/welcome_email.json

Fixes wellcomecollection/wellcomecollection.org#7134
Use `Library Enquiries <library@wellcomecollection.org>` for 'from' email address.

Update 'from' email

---

infra/scoped/api-gateway.tf
infra/scoped/api-model.tf
models/deletion-request.json
models/update-user.json
packages/apps/api/src/handlers/errorHandler.ts
packages/apps/api/src/handlers/user.ts
packages/apps/api/test/routes/users_user_id.test.ts
packages/apps/api/test/routes/users_user_id_deletion-request.test.ts
packages/apps/api/test/routes/users_user_id_password.test.ts

Some operations should require the user's current password to be validated in order for them to succeed. Rather than doing this in the client with 2 separate API calls, this PR makes it so that the relevant endpoints validate the password themselves.

Add password validation to significant operations

---

.buildkite/scripts/auth0-deployment.sh
.buildkite/scripts/auth0-packaging.sh
infra/scoped/auth0-connection.tf
packages/apps/auth0-actions/TaskWrapperPlugin.js
packages/apps/auth0-actions/src/create.ts
packages/apps/auth0-actions/src/delete.ts
packages/apps/auth0-actions/src/helpers.ts
packages/apps/auth0-actions/webpack.config.js

These scripts - `create` and `delete` don't actually modify Sierra, but Auth0 needs them

Add extra required scripts for legacy DB connections

---

packages/apps/auth0-actions/jest.setup.js
packages/apps/auth0-actions/src/change_email.ts
packages/apps/auth0-actions/src/databaseScriptGlobals.d.ts
packages/apps/auth0-actions/tests/change_email.test.ts

I tried to do the right thing here, but Auth0 is actually doing it for us - as per [this thread](https://community.auth0.com/t/changing-email-via-the-api-returns-the-specified-new-email-already-exists-when-it-doesnt/38838):
> Everything you do against that connection; registering, password resets, changing email, will trigger the GetUser request and query your local DB for a user with that email
(I have verified that this is the case)

It is not necessary to check whether a user exists before changing email

---

infra/scoped/auth0-client.tf
packages/apps/api/src/handlers/user.ts
packages/apps/api/test/routes/fixtures/mockedApi.ts
packages/apps/api/test/routes/users_user_id.test.ts
packages/apps/api/test/routes/users_user_id_deletion-request.test.ts
packages/apps/api/test/routes/users_user_id_password.test.ts
packages/apps/api/test/routes/users_user_id_validate.test.ts
smoke_tests/processorFunctions.js

- Client grants for everything that uses the identity API (ie, allow applications to request tokens for the new authorizer)
- Explicit dependence of endpoints on the caller token even when the URL parameter is not `me` - this makes broken access control (where users try to access resources they don't own) less likely
- Update the smoke test to request tokens for the new authorizer - these are backward-compatible with the existing authorizer because of the presence of the `openid` scope.

Additional authorizer bits and pieces

---

packages/apps/auth0-actions/package.json
packages/apps/auth0-actions/src/add_custom_claims.ts
packages/apps/auth0-actions/src/types/README.md
packages/apps/auth0-actions/src/types/post-login.ts
packages/apps/auth0-actions/tsconfig.build.json
packages/apps/auth0-actions/tsconfig.json
packages/shared/auth0-client/package.json

While the online editor has Typescript definitions built in, these don't seem to be publicly available - I've asked about this in the Auth0 forums: https://community.auth0.com/t/public-type-definitions-availability/74480.
In the mean time, each [trigger documentation page](https://auth0.com/docs/actions/triggers) contains a `Reference` section with details of the `Event` and `API` objects, so I've just replicated those docs here but in typescript form. Bit annoying, but at least they exist now.

Add type definitions for post-login action trigger

---

packages/apps/auth0-actions/src/add_custom_claims.ts
packages/apps/auth0-actions/src/types/post-login.ts
packages/apps/auth0-actions/tests/add_custom_claims.test.ts

- We only really need the barcode in the ID token, so let's only put it there
- The Auth0 docs tell us that:
> When creating your rule, make sure to set some logic that determines when to include additional claims. Injecting custom claims into every ID token that is issued is not ideal.
This is a good point! So I've done that: to request a custom claim, you need to ask for a scope of `weco:<claim_name>`.

Make custom claims better

---

infra/scoped/auth0-client.tf
infra/scoped/auth0-tenant.tf
infra/scoped/locals.tf

Refresh token rotation is a cool feature: https://auth0.com/docs/security/tokens/refresh-tokens/refresh-token-rotation
I've tested this by temporarily setting access token lifetimes to 10 seconds (everything still works seamlessly, which is cool)

Tighten up session config

---

.buildkite/pipeline.deploy.yml
.buildkite/pipeline.yml
jest.config.base.js
package.json
packages/apps/api-authorizer/package.json
packages/apps/api/package.json
packages/apps/auth0-actions/package.json
packages/apps/auth0-database-scripts/package.json
packages/shared/auth0-client/package.json
packages/shared/identity-common/package.json
packages/shared/sierra-client/package.json
packages/shared/sierra-client/tests/http-sierra-client.test.ts
yarn.lock

This does these things:
- Removes all unnecessary dependencies from the workspace root
- Gives each workspace the correct dependencies and devDependencies
- Hoists all dependencies to the workspace root, except for those required in Lambda packaging
- Stops bundling dev dependencies in Lambdas, reducing the Lambda package size from 42mb to 1.2mb. This improves deployment speed.

Sort out dependencies

---

packages/shared/auth0-client/package.json
packages/shared/auth0-client/src/HttpAuth0Client.ts
packages/shared/auth0-client/tests/mock-auth0-server.ts
packages/shared/identity-common/src/auth.ts
packages/shared/identity-common/src/index.ts
packages/shared/identity-common/tests/auth.test.ts
packages/shared/sierra-client/src/HttpSierraClient.ts
packages/shared/sierra-client/tests/mock-sierra-server.ts

We were requesting a new access token for every request in both the Auth0 and Sierra clients - this holds onto them until they expire.

Cache access tokens

---

infra/scoped/auth0-client.tf
packages/apps/api/src/handlers/user.ts
packages/apps/api/test/routes/fixtures/mockedApi.ts
packages/apps/auth0-actions/src/types/post-login.ts
packages/apps/auth0-actions/tests/add_custom_claims.test.ts
packages/apps/auth0-database-scripts/src/helpers.ts
packages/apps/auth0-database-scripts/tests/login.test.ts
packages/apps/auth0-database-scripts/tests/patronRecordToUser.test.ts
packages/shared/auth0-client/src/auth0.ts
packages/shared/sierra-client/src/HttpSierraClient.ts
packages/shared/sierra-client/src/MockSierraClient.ts
packages/shared/sierra-client/src/patron.ts
packages/shared/sierra-client/tests/http-sierra-client.test.ts
packages/shared/sierra-client/tests/patron.test.ts
packages/shared/sierra-client/tests/test-patron.ts

This maps the patron types from Sierra records into our own role-ish enum. "-ish", because "SelfRegistered" isn't really a role but as per discussion with @jtweed this is a pragmatic choice for integrating with Sierra and getting done what we need to be done.
The role in question gets stuck in the `app_metadata` and mapped into the SAML claims for use by OpenAthens

Map patron types into our own role definitions

---

packages/shared/sierra-client/src/HttpSierraClient.ts
packages/shared/sierra-client/tests/mock-sierra-server.ts
packages/shared/sierra-client/tests/test-patron.ts

This also updates the mock server to respect the `fields` parameter, such that existing tests will cover this behaviour

Make sure always to fetch the fields required to construct a patron

---

packages/shared/sierra-client/src/HttpSierraClient.ts
packages/shared/sierra-client/src/email-verification-notes.ts
packages/shared/sierra-client/tests/email-verification-notes.test.ts

The way that the Sierra patron update API works is a bit odd - you pass it an array, but it's non-destructive and it only actually takes heed of notes, messages, and patron image fields. Because of this, we only actually need to patch the notes varFields: this is very convenient, because it sidesteps an issue where an existing patron image field would cause any updates to fail due to the lack of support for this feature.

We only need to patch the notes varfields

---

.buildkite/scripts/aws-lambda-deployment.sh
.buildkite/scripts/aws-lambda-packaging.sh
infra/scoped/cloudwatch.tf
infra/scoped/iam.tf
infra/scoped/lambda.tf
infra/scoped/locals.tf
package.json
packages/apps/api-authorizer/src/authorization.ts
packages/apps/api-authorizer/src/handler.ts
packages/apps/patron-deletion-tracker/package.json
packages/apps/patron-deletion-tracker/src/app.ts
packages/apps/patron-deletion-tracker/test/deletion-tracker.test.ts
packages/apps/patron-deletion-tracker/tsconfig.build.json
packages/apps/patron-deletion-tracker/tsconfig.json
packages/shared/auth0-client/tests/mock-auth0-server.ts
tsconfig.base.json
tsconfig.build.json
yarn.lock

This is fairly predictable boilerplate for a CI-deployed TypeScript Lambda in this repo - some of the tf structure isn't ideal but this fits the existing pattern.
The diff is mostly because I blatted and recreated the `yarn.lock`; this also created some minor TS changes.

Add the infra and skeleton app for Patron deletion tracking

---

packages/shared/sierra-client/src/email-verification-notes.ts
packages/shared/sierra-client/tests/email-verification-notes.test.ts

If we can extract meaning from them, that's good enough. The fully readable string and the date are conveniences on top of a field which fundamentally just needs to store a verified email address.

Be more permissive when parsing verification notes

---

infra/scoped/lambda.tf
packages/apps/patron-deletion-tracker/jest.config.js
packages/apps/patron-deletion-tracker/package.json
packages/apps/patron-deletion-tracker/src/app.ts
packages/apps/patron-deletion-tracker/src/lambda.ts
packages/apps/patron-deletion-tracker/src/rate-limits.ts
packages/apps/patron-deletion-tracker/test/app.test.ts
packages/apps/patron-deletion-tracker/test/deletion-tracker.test.ts
packages/apps/patron-deletion-tracker/test/rate-limits.test.ts
packages/shared/sierra-client/src/MockSierraClient.ts
yarn.lock

Most of the lines here are tests - it was a real pain to test!
**What this PR does**:
- Implements a Lambda that looks for yesterday's deleted patrons in Sierra and deletes them in Auth0
- Respects the Auth0 API's rate limiting
- Gives good warnings if something goes wrong
**What this PR doesn't do** (but future PRs will):
- Wire up the Lambda to report errors to Slack
- Look at windows other than the previous day - this will become configurable via the event.

Implement the deletion tracking lambda

---

universal_login/deploy.ts
universal_login/emails/verify_email.json
universal_login/package.json
universal_login/scripts/auth0-management.ts
universal_login/scripts/aws.ts
universal_login/scripts/templates.ts
universal_login/yarn.lock

Currently the staging emails had to have the same `resultUrl` as the prod emails, which was a bit of a pain - this makes them more configurable, and refactors the deploy script across a few files

Make email templates a bit more configurable

---

universal_login/scripts/templates.ts

The changes in https://github.com/wellcomecollection/identity/pull/256 were a bit over-enthusiastic and replace all template strings they saw with "undefined" - this makes that script only replace template strings that it knows

Don't replace all template strings with "undefined"

---

infra/scoped/cloudwatch.tf
infra/scoped/locals.tf
packages/apps/patron-deletion-tracker/src/app.ts
packages/apps/patron-deletion-tracker/src/lambda.ts
packages/apps/patron-deletion-tracker/src/windows.ts
packages/apps/patron-deletion-tracker/test/app.test.ts
packages/apps/patron-deletion-tracker/test/windows.test.ts

There is going to be a local script for triggering deletion checks over the whole window that we're interested in, but I'm waiting until I can publish https://www.npmjs.com/package/@weco/ts-aws before I implement that

Make patron deletion windows wholly configurable

---

infra/scoped/cloudwatch.tf

See: https://github.com/wellcomecollection/platform-infrastructure/blob/a2d2ba64212a6d2f78570d73b6345b287c0517a3/monitoring/slack_alerts/lambda_errors_to_slack_alerts/src/lambda_errors_to_slack_alerts.py#L135-L139

Lambda error metric alarms have a naming convention

---

universal_login/prompt/login.json

We want to update the wording from 'Something went wrong, please try again later' to be more in line with our default wording to contact library enquiries. 
This PR doesn't approach the point of styling raised by the original ticket here https://github.com/wellcomecollection/wellcomecollection.org/issues/7594
There are two reasons for this: 
- In order to change styling we would need to have a custom error message, much like I was trying to achieve in [this PR](https://github.com/wellcomecollection/identity/pull/275). Having logic to raise a specific message each time we came up with a duplicate error in `get_user` and `login` will also mean we need to cover that use case across change password, update email etc. There is more detail in [the closed …

updating the login prompt 

---

infra/scoped/auth0-logs.tf

This is an optimisation to stop the Lambda being invoked constantly

Filter Auth0 successes in the Cloudwatch event rule

---

.buildkite/pipeline.deploy.yml

Stops errors when 2 PRs are merged around the same time

Limit concurrency for identity deployment

---

universal_login/prompt/reset-password.json
universal_login/templates/universal-login.html

We've noticed a small amount of errors whereby Sierra rejects a changed/reset password and shows a generic 'something went wrong' error to the user.
This is because Sierra has rules about 'trivial patterns' in password. 
Ticket: https://github.com/wellcomecollection/wellcomecollection.org/issues/7816
In this case, 'trivial patterns' are specifically repeated characters e.g. aaaa, ababab, abcabc. If you try to reset/change your password using your library account and you enter a new password with repeated characters and submit the form by clicking 'Update password', you'll get this message: 
We want to improve this. We have restrictions on what we can improve as we don't have much control over the appearance of error messaging in the login/reset/change password flow. 
It updates default …

Minimise errors relating to change/reset password 

---

infra/scoped/run_terraform.sh

I did a fresh checkout, and if you try to run Terraform straight away you get a non-obvious error:
```console
$ top
An error occurred (ParameterNotFound) when calling the GetParameter operation:
An error occurred (ParameterNotFound) when calling the GetParameter operation:
An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can't find the specified secret.
provider.auth0.domain
Enter a value: ^C
```
This is because `terraform workspace show` returns `default`, but we don't have SSM parameters for a default environment.
Now the Terraform wrapper script prompts you to select a workspace if it's not one it recognises:
```console
$ tfp
You must select a workspace before continuing, e.g. 'terraform workspace select stage'
```

Explain what's broken if you terraform without a workspace

---

infra/scoped/ecs_services.tf
infra/scoped/locals.tf

For https://github.com/wellcomecollection/platform/issues/5481 – this is (part of) why the catalogue API deployment is failing in staging; the requests API doesn't know how to find the catalogue API. 😢 
This just adds the new config parameter, and I've only deployed it to stage so far. Once I've seen it up and working, I'll deploy it to prod.
I'll remove the old Elasticsearch config in a separate PR, once we know everything is working and we know we won't be rolling back.

Add the catalogue API root config for the requests API

---

packages/apps/auth0-actions/src/add_custom_claims.ts
packages/apps/auth0-actions/tests/add_custom_claims.test.ts

Scope `weco:patron_role` returns `https://wellcomecollection.org/patron_role` containing roles, if present.

Update custom claims to support roles

---

infra/scoped/auth0-resource-server.tf
packages/apps/api-authorizer/src/handler.ts
packages/apps/api/src/app.ts
packages/apps/api/src/handlers/user.ts

Part of wellcomecollection/wellcomecollection.org#7808
Opted to create a new endpoint and handler instead of wrapping `updateUser` in conditionals based on whether we've got a password or not.
I think the `user_id` we're going to pass from the NextJS app will be prefixed with `auth0|` and I imagine we'll need to strip this off in order for the [`getTargetUserId` function](https://github.com/wellcomecollection/identity/blob/main/packages/apps/api/src/handlers/user.ts#L217-L238) not to blow up. I've seen elsewhere we're checking [if it starts with `auth0|p`](https://github.com/wellcomecollection/identity/blob/main/packages/shared/auth0-client/src/auth0.ts#L4) – I'm not sure where that `p` comes from (and it doesn't appear in the ids that I've been testing with)
__Edit:__ [I've removed the …

Create updateUserAfterRegistration endpoint

---

infra/scoped/api-gateway.tf
infra/scoped/api-integration.tf

Part of wellcomecollection/wellcomecollection.org#7808
Add API gateway required things (I think).

Post registration api gateway

---

packages/apps/auth0-actions/src/redirect_to_full_registration.ts
packages/apps/auth0-actions/tests/redirect_to_full_registration.test.ts

We were trying to check for appMetadata terms_and_conditions_accepted value as well as first and last name previously, if all these were present we returned i.e. skipped this redirect action. 
On testing with a current user, this if statement check was not working as expected and instead would keep trying to redirect. I've added a TODO to come back and improve the conditional, but for now to allow for current users who encounter this action after logging in, i've adjusted to check only for first and last name.

update action to check only for user first and last name 

---

infra/scoped/lambda.tf
packages/apps/api/src/app.ts
packages/apps/api/src/handlers/user.ts
packages/apps/api/src/server-lambda.ts
packages/apps/api/test/routes/fixtures/mockedApi.ts
packages/apps/api/tsconfig.json

We have a `createPatron` method available in sierra-client, let's make use of that in `updateUserAfterRegistration`. This means that the full registration form will collect firstName, lastName and update in auth0 and now also create a patron in sierra. 
This is towards overall work for https://github.com/wellcomecollection/wellcomecollection.org/issues/7896 and specifically for https://github.com/wellcomecollection/wellcomecollection.org/issues/8013

use createPatron in updateUserAfterRegistration

---

packages/apps/api/package.json
packages/shared/sierra-client/package.json
yarn.lock

`@weco/sierra-client` was already available in `tsconfig.json` but I forgot to include it in `package.json`. This should fix the 502 error on smoke tests for the identity api as the module should now be available.

make sure to include sierra-client in package.json

---

universal_login/templates/universal-login.html

I had the script in the `<head>` before, so it ran before the elements it was looking for existed in the DOM. Moving before the closing `</body>` tag to fix (and including a belt-and-braces check for the existence of the element before trying to change its style).

Make sure DOM has element we're targeting loaded

---

universal_login/templates/universal-login.html

It seems like we should be able to [encode/decode arbitrary data in the `state` parameter](https://github.com/auth0/nextjs-auth0/blob/a7a588d651eee571e7aa8ee881fbabbcd61153d6/src/auth0-session/hooks/get-login-state.ts#L35) on the Auth0 hosted form screens, but I haven't been able to make this work. For now I've resorted to checking the host is stage.

Check the host contains 'stage' to determine showing signup link

---

packages/shared/sierra-client/src/HttpSierraClient.ts

We want any patrons created from Membership Phase 1 via auth0 registration to have a note that tells us this. We will use this note as a way to delete patrons creating during testing, but we will also keep a note in place to indicate the registration is from auth0.

updating createPatron with note

---

packages/apps/auth0-database-scripts/src/create.ts
packages/shared/auth0-client/src/auth0.ts
packages/shared/sierra-client/src/HttpSierraClient.ts
packages/shared/sierra-client/src/SierraClient.ts
packages/shared/sierra-client/tests/http-sierra-client.test.ts

A user needs their password to be set on sierra, we can now do this at point of patron creation in create script. 
**Updated Note**: Based on a nifty suggestion by David I've added a new Auth0 type that contains password. 
**Note:** ~I've temporarily put a ts-ignore in for `user.password` as I can't see how to type this within the current existing type for Auth0User shown below, if anyone has any guidance on how best to type in this context it would be greatly appreciated. [Auth0 docs](https://auth0.com/docs/authenticate/database-connections/custom-db/templates/create#user-object-example) suggest that password is available from Auth0User.~
```
export type Auth0User = WithRequiredFields<
User<AppMetadata, UserMetadata>,
'user_id' | 'email' // These fields are always present
>;
```
related …

adding pin to createPatron

---

packages/apps/auth0-database-scripts/src/login.ts

We need to check at what point the login script is throwing an error so we can debug. Console logs contain strings and don't log out any information from the script beyond hard-coded line numbers.
related to work on https://github.com/wellcomecollection/wellcomecollection.org/issues/8071 and https://github.com/wellcomecollection/wellcomecollection.org/issues/7896

Temporary console logs to debug login script

---

packages/apps/auth0-database-scripts/src/create.ts
packages/shared/sierra-client/src/HttpSierraClient.ts

We need to create the patron in order to know the recordNumber (patron id), we can then set the patron's barcode as the patron id using updateBarcode. 
**Based on:**
- Testing sign up currently fails within login script
- I think the point of failure happens around `validateCredentials` as this expects a barcode and password, we have not set a barcode at patron creation
- We found current format of self registered patron's barcode is initially based on recordNumber
**Helpful to know:**
The format of barcode with self registered patron object on sierra 
```
{
"id": 12345,
"barcodes": [
"12345"
]
}
```
related to work on https://github.com/wellcomecollection/wellcomecollection.org/issues/8071 and https://github.com/wellcomecollection/wellcomecollection.org/issues/7896

implement a new updateBarcode method

---

packages/apps/auth0-actions/src/redirect_to_full_registration.ts

We don't want the action to bail out if a user's names are the temporary ones, as these represent the initial users in the first stage of sign up. We need them to progress to the next stage of the action, where we redirect to the full registration form, so we can update their firstName and lastName based on what they provide.
related to https://github.com/wellcomecollection/wellcomecollection.org/issues/8071 and overall https://github.com/wellcomecollection/wellcomecollection.org/issues/7896

Check for temporary names in action conditional

---

infra/scoped/auth0-connection.tf

Fixes the non-issue https://github.com/auth0/terraform-provider-auth0/issues/190
This makes `disable_signup` work for us

Fix change-ignoring for Auth0 connections

---

infra/scoped/secrets.tf

This means `AUTH0_ACTION_SECRET` is shared with weco frontend and secrets can stay in sync
Terrform plan
```
Terraform will perform the following actions:
~ resource "auth0_connection" "sierra" {
~ enabled_clients      = [
- "[redacted]",
]
id                   = "[redacted]"
name                 = "Sierra-Connection"
}
~ resource "aws_cloudwatch_event_rule" "auth0_logs" {
id             = "aws.partner/auth0.com/wellcomecollection-stage-[redacted]/auth0.logs/capture-auth0-errors-stage"
~ is_enabled     = false -> true
name           = "capture-auth0-errors-stage"
tags           = {}
}
+ resource "aws_secretsmanager_secret" "secret" {
+ arn                     = (known after apply)
+ id                      = (known after apply)
+ name                    = …
```

share the redirect_action_secret with experience account 

---

packages/apps/auth0-database-scripts/src/create.ts

in the hope it will come out in auth0 monitoring so we can see whether create script is running as expected.

adding logging to create script 

---

.buildkite/scripts/auth0-deployment.sh
infra/scoped/auth0-connection.tf
infra/scoped/data/empty.js
packages/apps/auth0-actions/add-debug-header.js
packages/apps/auth0-actions/package.json
packages/apps/auth0-database-scripts/TaskWrapperPlugin.js

Partly these are for my own notes; partly these are because Auth0/Buildkite was being distinctly weird earlier and we couldn't tell if it was actually updating the database action scripts or now.
Prepending the date and commit should make it easier to spot if/when Buildkite is updating the scripts, and when something is stuck.

Comments to make debugging this stuff easier

---

packages/apps/api/src/handlers/user.ts
packages/shared/auth0-client/src/Auth0Client.ts
packages/shared/auth0-client/src/HttpAuth0Client.ts
packages/shared/auth0-client/src/MockAuth0Client.ts
packages/shared/sierra-client/src/patron.ts

Once we get the first and lastname through to Identity api registration endpoint we need to be able to update their record on Sierra with the incoming first and lastname.

update patron first and lastname

---

packages/apps/api/src/handlers/user.ts
packages/shared/sierra-client/src/index.ts

I had required a function that I didn't make available properly resulting in an error 
```
"Error: Cannot find module '@weco/sierra-client/src/patron'\nRequire stack:\n- /var/task/handlers/user.js\n- /var/task/app.js\n- /var/task/server-lambda.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
```

make sure varFieldTags is available

---

packages/apps/api-authorizer/src/handler.test.ts
packages/apps/api-authorizer/src/handler.ts
packages/shared/auth0-client/src/auth0.ts

This is just the authorizer; there's another piece of work in the identity API to get it to recognise this `@machine` value, but I'll do that separately.

Set the principal ID to `@machine` for machine users

---

packages/apps/api/src/app.ts
packages/apps/api/src/handlers/user.ts
packages/apps/api/test/routes/fixtures/mockedApi.ts
packages/apps/api/test/routes/users_user_id_registration.test.ts
packages/shared/sierra-client/src/MockSierraClient.ts
packages/shared/sierra-client/src/index.ts
packages/shared/sierra-client/src/patron.ts

Closes #347
Inside the `PUT /users/{userId}/registration` endpoint, we now retrieve the existing patron record from Sierra before updating the first/last name.
This gives us some additional security on this endpoint: in particular, we'll reject updates for a patron if they don't have our Auth0 placeholder name `Auth0_Registration_undefined Auth0_Registration_tempLastName`.
This is the intended logic:
```mermaid
flowchart TD
GET{get patron<br/>from Sierra}
GET -- does not exist --> E404[HTTP 404<br/>Not Found]
GET -- other error --> E500[HTTP 500<br/>Internal Server Error]
GET --> MATCH{does stored<br/>name match<br/>the request?}
MATCH -- yes --> NOOP[no-op]
MATCH -- no --> PLACE{is stored name<br/>the placeholder?}
PLACE -- yes --> UPDATE[update name in Sierra<br/>HTTP 204 No Content] …
```

Check a user is mid-registration when updating their name

---

packages/apps/auth0-actions/src/redirect_to_full_registration.ts
packages/apps/auth0-actions/tests/redirect_to_full_registration.test.ts

Currently this interrupts the login flow, and takes the user to a `wc.org/account/success`, where they aren't logged in and don't have a valid session.
It's not obvious how we can redirect to that page and give them a valid session, so for now we're going to remove the `/success` page from the flow and send somebody straight to their account page.  This is simpler and means we're pretty close to having a working end-to-end flow.

Remove the redirect to the /success endpoint

---

infra/scoped/auth0-client.tf

This is already applied in staging.
For https://github.com/wellcomecollection/wellcomecollection.org/pull/8119
Without it, you get an error:

Allow sending somebody to the /success URL after logging out

---

packages/apps/api/src/handlers/user.ts

A small fix for the sign-up process, to make it create a useful MARC string.

Add a trailing comma to the surname of new users

---

packages/apps/api/test/routes/fixtures/mockedApi.ts
packages/apps/auth0-database-scripts/tests/login.test.ts
packages/apps/auth0-database-scripts/tests/patronRecordToUser.test.ts
packages/shared/sierra-client/src/HttpSierraClient.ts
packages/shared/sierra-client/src/MockSierraClient.ts
packages/shared/sierra-client/src/patron.ts
packages/shared/sierra-client/tests/http-sierra-client.test.ts
packages/shared/sierra-client/tests/mock-sierra-server.ts
packages/shared/sierra-client/tests/patron.test.ts
packages/shared/sierra-client/tests/test-patron.ts

We're going to use this to detect whether a user pre-dates the current sign-up process, and if so, skip implicit email verification.
This patch just fetches the `createdDate` field from Sierra; the next patch will actually use it.

Always fetch the createdDate of a patron from Sierra

---

universal_login/emails/blocked_account.html
universal_login/emails/reset_email.html
universal_login/emails/verify_email.html
universal_login/emails/welcome_email.html

If a user gets an email before they've set their name (for example, the initial email asking them to verify), we don't want to expose the placeholder name from the sign-up process.
In these cases, skip the greeting entirely.

Don't say "Hi, Auth0_Registration_undefined" in emails

---

universal_login/templates/universal-login.html

This is a somewhat hacky thing we did to prevent the sign-up links appearing outside staging; now we're ready to make sign-up live, we can remove it.

Don't hide the alternate action on prod

---

packages/apps/api/src/handlers/user.ts
packages/shared/sierra-client/src/HttpSierraClient.ts
packages/shared/sierra-client/src/index.ts
packages/shared/sierra-client/src/marc/index.ts
packages/shared/sierra-client/src/marc/names.ts
packages/shared/sierra-client/tests/marc/names.test.ts

For https://github.com/wellcomecollection/wellcomecollection.org/issues/8207; follows #363
Previously we had two slightly divergent implementations for creating a name varfield:
* When we create a user, we'd set field tag `n`, MARC tag 100 and subfields $a and $b
* When we updated a user, we'd set field tag `n` and subfields $a and $b, but no MARC tag 100
I think the omission of MARC tag 100 is causing us issues – e.g. in the Sierra GUI, a name without it is treated as opaque text rather than a structured MARC field.
This patch introduces a single implementation `createNameVarField()` which is used in both places, and gives us consistent behaviour.

Add a helper for creating the varField for a name

---

infra/modules/route/methods.tf
infra/scoped/api-gateway.tf
packages/apps/api-authorizer/src/handler.ts
packages/apps/api/src/app.ts
packages/apps/api/test/routes/users_user_id_send_verification_email.test.ts

For https://github.com/wellcomecollection/wellcomecollection.org/issues/8179
* Fix a Terraform issue where the `method` has to be created before the `method_response`; some hard-coding of the HTTP method as strings I did in #366 broke this ordering, but because I was only dealing with already-existing resources I didn't realise.
* Make the endpoint name consistent as `/send-verification-email`

Fix some deployment issues

---

infra/modules/route/methods.tf
infra/scoped/api-key.tf
infra/scoped/auth0-actions.tf
infra/scoped/auth0-client.tf
infra/scoped/auth0-connection.tf
infra/scoped/auth0-logs.tf
infra/scoped/auth0-tenant.tf
infra/scoped/lambda.tf
infra/scoped/locals.tf
infra/scoped/output.tf
infra/scoped/parameters.tf
infra/scoped/secrets.tf

There is no service called "Account Management System"; there's the identity web app in the dotorg repo. This name is a leftover Digirati-ism.
It'll be a bit of a faff to remove it completely, but we can start moving in that direction for resources that support easy renaming (including applications in Auth0 and API Gateway API keys).
I was actually trying to create a documented, turnkey process for devs to create clients that they could use when running the identity web app locally, but I got distracted by bad naming.
~This is currently applied in staging only; if we like it I'll apply it in prod then delete all the `moved` blocks.~ I had to apply in prod to deploy the "resend email verification" stuff, and this seemed harmless enough.

Remove some of the 'account management system' naming

---

packages/apps/auth0-database-scripts/src/login.ts

So that we're not telling users about the specifics of our infrastructure.

Throw a generic error for all error cases 

---

infra/scoped/iam-ci.tf

For https://github.com/wellcomecollection/identity/issues/372. Accompanies https://github.com/wellcomecollection/platform-infrastructure/pull/321. This should fix the broken deployments.

Define permissions for identity CI in this repo

---

infra/scoped/auth0-client.tf
infra/scoped/locals.tf
infra/scoped/output.tf
infra/scoped/secrets.tf

These can then be retrieved programatically to start a local copy of the identity web app.
For https://github.com/wellcomecollection/wellcomecollection.org/issues/8288

Export creds for a local dev client to Secrets Manager

---

universal_login/templates/universal-login.html

For https://github.com/wellcomecollection/wellcomecollection.org/issues/8289
I realised the page is being shown using our `universal-login.html` template, so I added a hard-coded workaround for this specific message. This is what the new page looks like:
It's obviously a bit unsatisfying to have a hacky fix, but it works and means we don't have to spend more time on this.

Don't show an "Enroll in multi-factor authentication" message to users

---

infra/scoped/auth0-tenant.tf

Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/8202
This is the new error when you try to sign up with an already-used email address:

Enable more specific errors for 'User already exists'

---

packages/apps/api/src/models/HttpError.ts
packages/apps/auth0-database-scripts/src/create.ts
packages/apps/auth0-database-scripts/src/get_user.ts
packages/shared/identity-common/src/index.ts
packages/shared/sierra-client/src/HttpSierraClient.ts
packages/shared/sierra-client/tests/http-sierra-client.test.ts

Last night we saw a smattering of errors when somebody tried to sign up. The underlying issue wasn't that they already had a Sierra account (which we already handle correctly); it's that they had **two**. This should be impossible – we cleaned up all the duplicate accounts before launching the new user sign-in, and Auth0 should prevent this from happening – but it did, and we give a less than helpful error:
This patch adds a `DuplicateUsers` response status from the `getRecordByEmail()` method on the Sierra client, and then we can respond to it with a more actionable error message:
This copy is based on a similar error which already works correctly on the sign-in screen:
I don't know why one error is in a red box and one is in inline text and I'm not going to spend the time to work it …

Improve the error message when somebody has multiple patron records

---

packages/apps/auth0-database-scripts/src/login.ts

When we throw a WrongUsernameOrPasswordError exception, this will appear as a "Failed Login (wrong password)" event in the Auth0 logs, e.g.
{
"date": "2023-01-12T13:45:57.493Z",
"type": "fp",
"description": "We don't recognise the email and/or password you entered. Please check your entry and try again.",
"user_id": "auth0|…",
"user_name": "example@example.com",
…
}
We throw it in two cases:
1.  Somebody enters an email address that we can't find in Sierra. There isn't a matching patron record, so we throw an error on L44.
2.  Somebody enters an email address that we can find in Sierra, but the password is incorrect, so we throw an error on L58.
Whatever we pass as the first argument to this exception will appear as the `user_id` in the Failed Login event, e.g.
throw new …

If Sierra doesn't validate a password, log the user ID, not the email

---

infra/scoped/.terraform.lock.hcl
infra/scoped/auth0-tenant.tf
infra/scoped/parameters.tf
infra/scoped/terraform.tf

As part #384 we want to make sure the colours are up to date with the new scheme. We've determined they didn't need to be stored in variables and hard coded them.

Remove colour local variables and hard code new color scheme hex codes

---

infra/scoped/auth0-client.tf
infra/scoped/locals.tf
infra/scoped/output.tf
infra/scoped/provider.tf
infra/scoped/secrets.tf

This change adds an Auth0 client for the staging and production tenants. This is required in order to allow the IIIF Image APIs to authenticate and authorize users to view restricted images.
This change creates secrets in the Digirati AWS account that can be consumed to configure the Image API service at the paths:
- `wellcome/identity/[stage|prod]/iiif_image_api/auth0_client_id`
- `wellcome/identity/[stage|prod]/iiif_image_api/auth0_client_secret`
Related to: https://github.com/wellcomecollection/identity/pull/403
Part of: https://github.com/wellcomecollection/platform/issues/5747 
> [!WARNING]
> This terraform change is applied, until this is merged other terraform changes are blocked.
```console
Terraform will perform the following actions:
+ resource "auth0_client" "iiif_image_api" { …
```

Adds an Auth0 client for the IIIF Image APIs

---

infra/scoped/auth0-connection.tf

This change follows https://github.com/wellcomecollection/identity/pull/405 and is required to allow this client to authenticate Sierra users (oops)!
Part of: https://github.com/wellcomecollection/platform/issues/5747 
> [!WARNING]
> This terraform change is applied, until this is merged other terraform changes are blocked.
The test app https://tomcrane.github.io/iiif-auth-client/?manifest=https://iiif.wellcomecollection.org/presentation/b20146267,  doesn't lead you to an error with `?error=invalid_request&error_description=no%20connections%20enabled%20for%20the%20client` in the URL.
Moving closer to getting access to restricted items for users with the right roles.
This change impacts only existing as yet to be used app clients, so should not impact other users.

Add IIIF Image API client to Sierra database connection

---

infra/scoped/locals.tf

This change adds the correct callback and logout URLs for the IIIF Image application in Auth0 that allows restricted logins to occur.
Part of https://github.com/wellcomecollection/platform/issues/5747
See https://wellcome.slack.com/archives/CBT40CMKQ/p1723462603970219?thread_ts=1720700716.827569&cid=CBT40CMKQ
```
Terraform will perform the following actions:
~ resource "auth0_client" "iiif_image_api" {
~ allowed_logout_urls                 = [
"https://iiif.wellcomecollection.org/auth/v2/access/2/eden/logout",
+ "https://iiif.wellcomecollection.org/auth/v2/access/2/restrictedlogin/logout",
]
id                                  = "REDACTED"
name                                = "IIIF Image API"
}
Plan: 0 to add, 1 to change, 0 to destroy.
```
> [!NOTE]
> This change has already been …

Add callback and logout URLs for IIIF image app

---

infra/scoped/auth0-actions.tf
infra/scoped/auth0-client.tf
infra/scoped/auth0-logs.tf
infra/scoped/backend.tf
infra/scoped/cloudwatch.tf
infra/scoped/terraform.tf

Deprecation warning, see https://wellcome.slack.com/archives/CQ720BG02/p1738588477106949
Apply to stage workspace and see whether the deprecation warning stop popping up in the alert channel
The deprecation warning stop popping up in the alert channel
This is set up with separate stage/prod workspace so we can check things are fine before applying to prod
```
Terraform will perform the following actions:
~ resource "auth0_client_grant" "buildkite" {
id        = "cgr_mAD3ICX6y2cGDpLb"
~ scope     = [
"delete:log_streams",
+ "read:connections_options",
+ "update:connections_options",
]
}
~ resource "aws_lambda_function" "main" {
id                             = "identity-api-stage"
tags                           = {
"name" = "identity-authorizer-stage"
}
~ environment {
~ variables = …
```

add auth0 permissions for buildkite
