wellcomecollection/identity

docs/adr/0000-use-markdown-architectural-decision-records.md
docs/adr/0001-selection-of-identity-management-platform.md
docs/adr/index.md
docs/adr/template.md

Includes:
- ADR template and index
- 0001 Selection Identity Management Platform

Creation of initial Architectural Decision Records (ADR)

---

infra/scoped/auth0-client.tf
packages/apps/api/src/app.ts
packages/apps/api/src/handlers/user.ts
packages/shared/auth0-client/src/index.ts
packages/shared/auth0-client/tests/auth0-client.test.ts
packages/shared/sierra-client/src/index.ts
packages/shared/sierra-client/tests/sierra-client.test.ts

This PR implements the Lambda Function and associated logic that supports the updating of user records across both Auth0 and Sierra. As it stands, this extends only to email addresses.

Implements user update Lambda Function

---

.buildkite/scripts/init-environment.sh
infra/scoped/api-key.tf
infra/scoped/auth0-client.tf
infra/scoped/output.tf
infra/scoped/variables.tf
packages/apps/api/src/app.ts
packages/apps/api/src/handlers/user.ts
packages/shared/auth0-client/src/index.ts
packages/shared/auth0-client/tests/auth0-client.test.ts
packages/shared/sierra-client/src/index.ts
packages/shared/sierra-client/tests/sierra-client.test.ts

Also applies a few minor cleanups to the Terraform and build process.

Adds Account Management System as an Auth0 client and API key

---

packages/account-management/src/frontend/index.tsx

As requested by Ville in UX review

Moves scroll bar out of registration view

---

packages/account-management/src/frontend/Registration/AccountValidated.tsx

Adds redirect to the `/login` page from the `/validated `route.

Redirect to login

---

infra/scoped/api-documentation/api.json
infra/scoped/api-documentation/users/:user_id/delete.json
infra/scoped/api-documentation/users/:user_id/deletion-request/delete.json
infra/scoped/api-documentation/users/:user_id/get.json
infra/scoped/api-documentation/users/:user_id/lock/put.json
infra/scoped/api-documentation/users/:user_id/put.json
infra/scoped/api-documentation/users/:user_id/reset-password/put.json
infra/scoped/api-documentation/users/:user_id/send-verification/put.json
infra/scoped/api-documentation/users/:user_id/unlock/put.json
infra/scoped/api-documentation/users/get.json
infra/scoped/api-documentation/users/post.json
models/user-list.json
models/user.json
packages/apps/api-authorizer/src/index.ts
packages/apps/api/src/models/user.ts
packages/shared/auth0-client/src/auth0.ts
packages/shared/auth0-client/tests/auth0-client.test.ts

Also fixes a few documentation issues and breaks out the documentation into sections describing which role can access which calls.

Adds 'lastLoginDate' to user API results

---

README.md

Tiny README change to make it a bit easier to start working in this repo.

Add a note about needing pre-commit

---

README.md

Add some detail about pinned tf version and workspaces.

Update README to include terraform gotchas

---

packages/apps/api-authorizer/src/handler.ts
packages/apps/api-authorizer/src/resourceAcls.ts

Quick refactor ahead of adding the requesting endpoint

Constant-time ACL lookups

---

infra/scoped/ecs_services.tf
infra/scoped/lambda.tf
infra/scoped/secrets.tf

Some resources were poorly configured to work in the context of multiple workspaces - this fixes those

Per-environment resources

---

infra/scoped/api-documentation.tf
infra/scoped/api-documentation/users/:user_id/delete-401.json
infra/scoped/api-documentation/users/:user_id/delete-403.json
infra/scoped/api-documentation/users/:user_id/deletion-request/delete-401.json
infra/scoped/api-documentation/users/:user_id/deletion-request/delete-403.json
infra/scoped/api-documentation/users/:user_id/deletion-request/put-401.json
infra/scoped/api-documentation/users/:user_id/deletion-request/put-403.json
infra/scoped/api-documentation/users/:user_id/get-401.json
infra/scoped/api-documentation/users/:user_id/get-403.json
infra/scoped/api-documentation/users/:user_id/item-requests/get-401.json
infra/scoped/api-documentation/users/:user_id/item-requests/get-403.json
infra/scoped/api-documentation/users/:user_id/item-requests/post-401.json
infra/scoped/api-documentation/users/:user_id/item-requests/post-403.json
infra/scoped/api-documentation/users/:user_id/lock/delete-401.json
infra/scoped/api-documentation/users/:user_id/lock/delete-403.json
infra/scoped/api-documentation/users/:user_id/lock/put-401.json
infra/scoped/api-documentation/users/:user_id/lock/put-403.json
infra/scoped/api-documentation/users/:user_id/password/put-401.json
infra/scoped/api-documentation/users/:user_id/password/put-403.json
infra/scoped/api-documentation/users/:user_id/put-401.json
infra/scoped/api-documentation/users/:user_id/put-403.json
infra/scoped/api-documentation/users/:user_id/reset-password/put-401.json
infra/scoped/api-documentation/users/:user_id/reset-password/put-403.json
infra/scoped/api-documentation/users/:user_id/send-verification/put-401.json
infra/scoped/api-documentation/users/:user_id/send-verification/put-403.json
infra/scoped/api-documentation/users/get-401.json
infra/scoped/api-documentation/users/get-403.json
infra/scoped/api-gateway.tf
packages/apps/api-authorizer/src/handler.ts
packages/apps/api-authorizer/tests/api-authorizer.test.ts

This is very pedantic but there we are - resolves https://github.com/wellcomecollection/identity/issues/136

Reject unauthorized requests with a 401, not a 403

---

smoke_tests/identityApi.yaml
smoke_tests/processorFunctions.js

Add a smoke test for the `/users/me/item-requests` endpoint endpoint to increase deployment reliability.

Add smoke test for /users/:id:/item-requests endpoint

---

README.md

Update the docs to describe the build process a bit better.

Update README to include some docs about build

---

packages/apps/auth0-actions/src/login.ts
packages/shared/sierra-client/src/client.ts
packages/shared/sierra-client/tests/sierra-client.test.ts

Resolves https://github.com/wellcomecollection/identity/issues/135

Use the Sierra patrons/auth endpoint for credential validation

---

package.json
packages/shared/auth0-client/tests/auth0-client.test.ts
packages/shared/sierra-client/tests/sierra-client.test.ts
yarn.lock

Use jest for assertions

---

infra/scoped/ecs_services.tf

Read the correct secrets to be able to read from Elasticsearch.
Follows https://github.com/wellcomecollection/catalogue-api/pull/173

Read updated secrets from catalogue-api stack

---

packages/apps/auth0-actions/jest.config.js
packages/apps/auth0-actions/jest.setup.js
packages/apps/auth0-actions/package.json
packages/apps/auth0-actions/src/create_azure_ad_profile.ts
packages/apps/auth0-actions/src/enrich_userinfo.ts
packages/apps/auth0-actions/src/get_user.ts
packages/apps/auth0-actions/src/login.ts
packages/apps/auth0-actions/src/patronRecordToUser.ts
packages/apps/auth0-actions/tests/create_azure_ad_profile.test.ts
packages/apps/auth0-actions/tests/enrich_userinfo.test.ts
packages/apps/auth0-actions/tests/get_user.test.ts
packages/apps/auth0-actions/tests/login.test.ts
packages/apps/auth0-actions/tests/patronRecordToUser.test.ts
packages/apps/auth0-actions/tsconfig.json
yarn.lock

Does what it says on the tin, I also tightened up some of the types a bit.

Add tests for Auth0 actions

---

infra/scoped/auth0-connection.tf
infra/scoped/auth0-rule.tf
infra/scoped/data/.gitignore
infra/scoped/data/empty.js
infra/scoped/lambda.tf

This matches what the Lambda functions were already doing

Remove tf dependence on non-existent/compiled resources

---

packages/apps/api-authorizer/src/handler.ts

I grepped for the words "console" "log" "debug" and "info" and removed anything that looked like PII.
For https://github.com/wellcomecollection/platform/issues/5166

Remove debug logs that include access tokens and user info

---

.gitignore
README.md
infra/scoped/api-gateway.tf
infra/scoped/ecs_services.tf
infra/scoped/locals.tf
infra/scoped/output.tf
infra/scoped/terraform.tf

Terraform 0.15 is picky about sensitive outputs: https://www.terraform.io/upgrade-guides/0-15.html#sensitive-output-values
Plus adding some tags and other small fixes.

Miscellaneous Terraform fixes

---

packages/apps/api/src/app.ts
packages/apps/api/src/handlers/errorHandler.ts
packages/apps/api/src/handlers/user.ts
packages/apps/api/src/models/HttpError.ts

This makes the identity API use the same error handling logic everywhere (hence the large diff). 
There are no tests for this app, so those are coming up in a separate PR to make sure I haven't broken anything.
The part that fixes the bug is https://github.com/wellcomecollection/identity/pull/175/files#diff-e7bd22e600a28efd6644ba0a4f4d5c42ecd9c154360e1e0aa162df38ffbca58dR641-R669

Fix 500 for unauthenticated "me" calls

---

packages/apps/api/package.json
packages/apps/api/src/app.ts
packages/apps/api/src/handlers/user.ts
yarn.lock

Introduced this issue in https://github.com/wellcomecollection/identity/pull/175, found it in https://github.com/wellcomecollection/identity/pull/177

Catch errors thrown in async route handlers

---

packages/apps/auth0-actions/src/login.ts
packages/apps/auth0-actions/tests/login.test.ts

Don't tell users who are already in Sierra to verify their emails

---

infra/scoped/secrets.tf

Some more leftover infra from identity-admin.

Remove unused identity-admin secrets

---

.buildkite/scripts/auth0-deployment.sh

Leftover from https://github.com/wellcomecollection/identity/pull/194

Fix deployment

---

universal_login/prompt/reset-password.json

Fixes wellcomecollection/wellcomecollection.org#7133

Use consistent 'sign in' language

---

.buildkite/pipeline.yml
package.json
packages/apps/api/package.json

Make sure email templates are copied into the lambda zip

---

universal_login/emails/welcome_email.json

☝️ 
Solves [#7142](https://github.com/wellcomecollection/wellcomecollection.org/issues/7142#issuecomment-965070617) until we need to handle membership.

Disable welcome email

---

packages/apps/api/package.json
universal_login/emails/verify_email.html
universal_login/emails/verify_email.json
universal_login/emails/welcome_email.html
universal_login/emails/welcome_email.json

Fixes wellcomecollection/wellcomecollection.org#7142

Update welcome and verify email templates

---

packages/apps/api-authorizer/src/handler.ts

Deny access by default

---

packages/apps/api/src/handlers/user.ts
packages/apps/api/test/routes/users_user_id_password.test.ts
packages/apps/auth0-actions/jest.setup.js
packages/apps/auth0-actions/src/change_email.ts
packages/apps/auth0-actions/src/change_password.ts
packages/apps/auth0-actions/src/databaseScriptGlobals.d.ts
packages/apps/auth0-actions/tests/change_email.test.ts
packages/apps/auth0-actions/tests/change_password.test.ts
packages/shared/auth0-client/src/HttpAuth0Client.ts
packages/shared/auth0-client/src/MockAuth0Client.ts
packages/shared/sierra-client/src/MockSierraClient.ts

We do these in custom DB scripts now; some of the functionality they added has been moved into said scripts

Removing Sierra mutations from the API

---

infra/scoped/auth0-client.tf
infra/scoped/auth0-resource-server.tf

This tells Auth0 that we will be creating a resource server (this will be in the custom authorizer) which will be able to validate tokens

Add resource server (aka custom API)

---

packages/apps/api-authorizer/src/handler.ts
packages/apps/api-authorizer/src/index.ts

Turns out we were constructing the issuer string incorrectly

Fix authorizer

---

universal_login/templates/universal-login.html

Fixes wellcomecollection/wellcomecollection.org#7345

Add text to login screen

---

infra/scoped/auth0-connection.tf
infra/scoped/auth0-resource-server.tf
infra/scoped/locals.tf

So we don't accidentally blat these when applying

Put the dev client authorizations into terraform

---

infra/scoped/locals.tf

cf https://github.com/wellcomecollection/wellcomecollection.org/pull/7423

Callback URL has moved

---

infra/scoped/auth0-client.tf

These are already applied on stage

Config changes to make login work

---

packages/apps/auth0-actions/jest.config.js
packages/apps/auth0-actions/package.json
packages/apps/auth0-actions/src/add_custom_claims.ts
packages/apps/auth0-actions/tests/add_custom_claims.test.ts
packages/apps/auth0-actions/tsconfig.build.json
yarn.lock

The terminology here (ie claims) is really bizarre but upshot is that we'll have all the patron data we need upon login, and so won't need to fetch extra data from Auth0 or Sierra.

Add the barcode to access/ID tokens

---

packages/apps/auth0-database-scripts/src/verify.ts

Email verification seems to work strangely, sometimes updating immediately and sometimes not. Perhaps it's just eventually consistent, but this seemed like a good bit of uncertainty to resolve before digging elsewhere.

Maybe better email verification

---

packages/apps/auth0-database-scripts/src/login.ts
packages/apps/auth0-database-scripts/tests/login.test.ts

Stop verifying email addresses on login

---

packages/shared/auth0-client/package.json
packages/shared/auth0-client/tests/auth0-client.test.ts
packages/shared/auth0-client/tests/mock-auth0-server.ts
packages/shared/auth0-client/tests/test-user.ts
packages/shared/auth0-client/tsconfig.build.json
packages/shared/auth0-client/tsconfig.json
packages/shared/sierra-client/package.json
packages/shared/sierra-client/src/HttpSierraClient.ts
packages/shared/sierra-client/src/patron.ts
packages/shared/sierra-client/tests/http-sierra-client.test.ts
packages/shared/sierra-client/tests/mock-sierra-server.ts
packages/shared/sierra-client/tests/test-patron.ts
packages/shared/sierra-client/tsconfig.build.json
packages/shared/sierra-client/tsconfig.json
yarn.lock

These tests leave a little to be desired imo but this is largely a like-for-like replacement rather than an improvement. This work is in service of upcoming changes to these clients which will mean they don't fetch a new token for every request.

Replace moxios with MSW

---

packages/apps/auth0-database-scripts/src/change_email.ts
packages/apps/auth0-database-scripts/tests/change_email.test.ts
packages/shared/sierra-client/src/HttpSierraClient.ts
packages/shared/sierra-client/src/MockSierraClient.ts
packages/shared/sierra-client/src/SierraClient.ts
packages/shared/sierra-client/src/email-verification-notes.ts
packages/shared/sierra-client/tests/http-sierra-client.test.ts

This adds the ability to mark the patron's current email verified

(2) Add verification notes to Sierra client

---

packages/apps/api-authorizer/README.md
packages/apps/api/README.md
packages/apps/auth0-actions/README.md
packages/apps/patron-deletion-tracker/README.md
packages/shared/auth0-client/README.md
packages/shared/identity-common/README.md
packages/shared/sierra-client/README.md

These are very minimal but they do at least explain what each package does. There was already one there for the database scripts.

Add READMEs for all packages

---

packages/shared/sierra-client/jest.config.js
packages/shared/sierra-client/package.json
packages/shared/sierra-client/src/HttpSierraClient.ts
packages/shared/sierra-client/src/MockSierraClient.ts
packages/shared/sierra-client/src/SierraClient.ts
packages/shared/sierra-client/src/pagination.ts
packages/shared/sierra-client/tests/global.d.ts
packages/shared/sierra-client/tests/http-sierra-client.test.ts
packages/shared/sierra-client/tests/mock-sierra-server.ts
packages/shared/sierra-client/tests/pagination.test.ts
packages/shared/sierra-client/tsconfig.json
yarn.lock

Add a method to the Sierra client for fetching deleted patrons

---

packages/shared/auth0-client/src/Auth0Client.ts
packages/shared/auth0-client/src/HttpAuth0Client.ts
packages/shared/auth0-client/src/MockAuth0Client.ts
packages/shared/auth0-client/tests/auth0-client.test.ts
packages/shared/auth0-client/tests/mock-auth0-server.ts

Very simple to the point of being a bit pointless but there we go, turning the crank

Add a deletion method to the Auth0 client

---

packages/shared/sierra-client/src/patron.ts

And some added mysterious autoformatting

Add some more patron types to the Staff role

---

infra/scoped/.terraform.lock.hcl
infra/scoped/auth0-client.tf
infra/scoped/locals.tf
infra/scoped/terraform.tf

See https://auth0.com/docs/authenticate/login/auth0-universal-login/configure-default-login-routes
Resolves https://github.com/wellcomecollection/identity/issues/263

Add default login URLs for applications

---

packages/shared/sierra-client/src/patron.ts
packages/shared/sierra-client/tests/patron.test.ts

Resolves https://github.com/wellcomecollection/wellcomecollection.org/issues/7787

Add a couple more Staff patron types

---

.pre-commit-config.yaml
infra/scoped/lambda.tf
packages/apps/patron-deletion-tracker/package.json
packages/apps/patron-deletion-tracker/scripts/remove-all-deleted-patrons.ts
packages/apps/patron-deletion-tracker/src/app.ts
packages/apps/patron-deletion-tracker/src/rate-limits.ts
packages/apps/patron-deletion-tracker/tsconfig.build.json
packages/apps/patron-deletion-tracker/tsconfig.json
packages/shared/sierra-client/src/HttpSierraClient.ts
packages/shared/sierra-client/tests/http-sierra-client.test.ts
tsconfig.base.json
yarn.lock

This does what it says on the tin, and also fixes a few bugs in the deletion tracker. Don't be afraid of the diff - it's almost all `yarn.lock`!

Add ability to invoke deletion tracker from a script

---

infra/scoped/lambda.tf

Saw a timeout in the logs, this might fix it.

Bump authorizer timeout

---

infra/scoped/auth0-client.tf
infra/scoped/auth0-logs.tf
infra/scoped/locals.tf

These events will then be handled by https://github.com/wellcomecollection/platform-infrastructure/pull/288

Stream logs into our monitoring stack

---

universal_login/deploy.ts

Saw errors related to this, hopefully will fix it

Drop the email template deployment rate limit further

---

infra/scoped/auth0-client.tf

See https://github.com/wellcomecollection/identity/issues/277#issuecomment-1077632386

Bump Refresh Token Rotation leeway

---

infra/scoped/auth0-logs.tf

Required for https://github.com/wellcomecollection/platform-infrastructure/pull/291

Pass log event descriptions to the monitoring Lambda

---

universal_login/prompt/reset-password.json

We need to reduce the characters in 'description' to be below 200, above 200 characters causes a failure. This PR gives us 196 characters.

Fix/minimise passwordchange error - reduce number of characters

---

packages/apps/auth0-database-scripts/src/change_password.ts
packages/shared/auth0-client/src/HttpAuth0Client.ts
universal_login/templates/universal-login.html

My [previous approach](https://github.com/wellcomecollection/identity/pull/282) to adding a description and note telling users about trivial/repeated pattern passwords wasn't going to work. This time I have gone about improving error in HttpAuth0Client and surfacing a further improved error message at point of error for repeated patterns in changed passwords.
This relates to https://github.com/wellcomecollection/wellcomecollection.org/issues/7816

Minimise errors relating to changing/reseting password 

---

infra/scoped/ecs_services.tf

Relates to https://github.com/wellcomecollection/catalogue-api/pull/386, should fix deployment

Remove ES secrets from requests API ECS config

---

packages/apps/api/src/handlers/user.ts
packages/shared/auth0-client/src/Auth0Client.ts
packages/shared/auth0-client/src/HttpAuth0Client.ts
packages/shared/auth0-client/src/MockAuth0Client.ts
packages/shared/auth0-client/tests/auth0-client.test.ts

Part of wellcomecollection/wellcomecollection.org#7808
Save the user's names to Auth0 after registration completion

Add updateNames method to the Auth0Client

---

.buildkite/Dockerfile
smoke_tests/Dockerfile
universal_login/Dockerfile

For wellcomecollection/platform#5545, which includes a discussion of the benefits.

Use Docker images from ECR Public

---

universal_login/prompt/login.json

I can't quite figure out what Auth0 expects from me for the [configuration values for login](https://auth0.com/docs/customize/universal-login-pages/universal-login-page-templates) – they're not currently displaying, so trying something else to go to stage.

Try with signupActionText

---

universal_login/prompt/login.json

Running out of ideas

---

universal_login/prompt/login.json

Change text we can already see to check if deploy is working for Auth0 Widget

Auth0 widget content test

---

universal_login/templates/universal-login.html

Test showing all prompt screen texts

---

packages/shared/sierra-client/src/HttpSierraClient.ts

I want just the json body for creation of a patron, so I don't need params
https://sandbox.iii.com/iii/sierra-api/swagger/index.html#!/patrons/Create_a_patron_record_post_0

Remove param from data in POST for createPatron

---

packages/apps/auth0-actions/src/redirect_to_full_registration.ts
packages/apps/auth0-actions/src/types/post-login.ts
packages/apps/auth0-actions/tests/redirect_to_full_registration.test.ts

☝️ 
Required for wellcomecollection/wellcomecollection.org#8076

Add email to sessionToken

---

packages/apps/api-authorizer/src/handler.ts

Logging out whole `APIGatewayRequestAuthorizerEvent` temporarily, also, check for undefined token ~and throw error if token is undefined~ and log it

More logging

---

packages/apps/api-authorizer/src/handler.ts

We no longer need these for debugging purposes, tidying them up 🧹

remove logs we no longer need

---

packages/apps/auth0-actions/src/redirect_to_full_registration.ts
packages/apps/auth0-actions/tests/redirect_to_full_registration.test.ts

Point to the correct url for the registration form

---

packages/apps/auth0-database-scripts/src/change_password.ts
packages/apps/auth0-database-scripts/src/create.ts
packages/apps/auth0-database-scripts/tests/change_password.test.ts
packages/shared/sierra-client/src/HttpSierraClient.ts
packages/shared/sierra-client/src/MockSierraClient.ts
packages/shared/sierra-client/src/SierraClient.ts
packages/shared/sierra-client/src/patron.ts

This can take options like barcode and varFieldTags to change patron details via PUT. 
Based on https://github.com/wellcomecollection/wellcomecollection.org/issues/8073 and suggestion from @jamieparkinson  here https://github.com/wellcomecollection/wellcomecollection.org/issues/8073#issuecomment-1156277878
and overall related to https://github.com/wellcomecollection/wellcomecollection.org/issues/7896

implement a generic updatePatron method 

---

infra/scoped/auth0-actions.tf

Add a note about "fixing" the redirect to localhost issues

---

README.md

I can only just hold the different pieces in my head; writing it down is meant to help me remember what's what.
Rendered version: https://github.com/wellcomecollection/identity/blob/alexwlchan-patch-1/README.md

Add a brief summary of key services and what's in this repo

---

packages/apps/api/src/handlers/user.test.ts
packages/apps/api/src/handlers/user.ts

Accompanies https://github.com/wellcomecollection/identity/pull/344

Recognise the `@machine` caller ID in the identity API

---

universal_login/templates/universal-login.html

Based on https://github.com/wellcomecollection/wellcomecollection.org/issues/7814
I've also added whitespace to make this page a little easier to follow.

Update the user-facing text on the "apply for a membership" page

---

universal_login/templates/universal-login.html

For https://github.com/wellcomecollection/wellcomecollection.org/issues/8160 and https://github.com/wellcomecollection/wellcomecollection.org/issues/8178

More markups to the user-facing sign-up copy

---

infra/scoped/parameters.tf
infra/scoped/secrets.tf
smoke_tests/processorFunctions.js

For https://github.com/wellcomecollection/identity/issues/372; accompanies https://github.com/wellcomecollection/wellcomecollection.org/pull/8282
This change is already applied.

Rename all the parameters to identity_web_app

---

packages/apps/auth0-database-scripts/src/create.ts

Closes https://github.com/wellcomecollection/identity/issues/379
I couldn't work out how to deploy locally, so I tested this by editing the Auth0 database action in staging directly. Example:

Improve the sign-up error message when somebody has a trivial password

---

packages/apps/api/src/utils/templates/delete-request_admin_body.liquid
packages/apps/api/src/utils/templates/delete-request_user_body.liquid
universal_login/emails/blocked_account.html
universal_login/emails/reset_email.html
universal_login/emails/verify_email.html
universal_login/emails/welcome_email.html
universal_login/templates/universal-login.html

Closes #[8593](https://github.com/wellcomecollection/wellcomecollection.org/issues/8593)

Change colours to reflect new palette

---

infra/modules/ecs_service/main.tf
infra/modules/ecs_service/variables.tf
infra/scoped/ecs_services.tf

For https://github.com/wellcomecollection/platform/issues/5631

Remove all the weco-deploy related tags from ECS services

---

infra/modules/ecs_service/main.tf

Bump ECS module versions to access updated firelens container

---

.buildkite/scripts/linting.sh
infra/scoped/.terraform.lock.hcl
packages/apps/api/src/handlers/user.ts
packages/apps/api/test/routes/users_user_id_registration.test.ts
packages/apps/auth0-actions/src/redirect_to_full_registration.ts
packages/apps/auth0-actions/src/types/post-login.ts
packages/apps/auth0-actions/tests/redirect_to_full_registration.test.ts
packages/apps/auth0-database-scripts/src/create.ts
packages/apps/auth0-database-scripts/src/databaseScriptGlobals.d.ts
packages/shared/auth0-client/src/auth0.ts
packages/shared/identity-common/src/auth.ts
packages/shared/identity-common/src/index.ts
packages/shared/sierra-client/package.json
packages/shared/sierra-client/src/HttpSierraClient.ts
packages/shared/sierra-client/src/MockSierraClient.ts
packages/shared/sierra-client/src/patron.ts
packages/shared/sierra-client/tests/http-sierra-client.test.ts
universal_login/emails/blocked_account.html
universal_login/emails/reset_email.html
universal_login/emails/verify_email.html
universal_login/emails/welcome_email.html
yarn.lock

There are a few deletions here which might seem odd, and I'm going to add some comments to the PR explaining them

Registration tweaks

---

infra/scoped/.terraform.lock.hcl
infra/scoped/acm.tf
infra/scoped/api-stage.tf
infra/scoped/auth0-tenant.tf
infra/scoped/provider.tf
infra/scoped/route53.tf
infra/scoped/s3.tf
infra/scoped/variables.tf

I've done all the state wrangling in both stage and prod to make this a no-op.
For https://github.com/wellcomecollection/platform/issues/5664 and https://github.com/wellcomecollection/platform/issues/5677

Use the new Terraform module to create ACM certificates

---

infra/scoped/terraform.tf

For https://github.com/wellcomecollection/aws-account-infrastructure/issues/2

Point at the new location of the remote account state

---

infra/scoped/.terraform.lock.hcl
infra/scoped/auth0-actions.tf
infra/scoped/lambda.tf

This is already applied, it will hopefully fix failing deployments 🤞

Bump all Lambdas to node 18

---

infra/scoped/auth0-actions.tf
infra/scoped/locals.tf

Use correct URL for identity app

---

CODEOWNERS

I've added a default code owner so they automatically get added to PRs as reviewers.
Once it's in, and a PR gets created we could check it adds it automatically to reviewers
PRs not going unnoticed anymore 
I don't think there is any

Add codeowner file for developers team

---

.buildkite/scripts/init-environment.sh

The addition of the subshell in order to fail properly inside a function that creates and source the env file, hides the env vars from the parent shell. This change fixes that issue by moving sourcing the file to outside the function.
Run this in CI, does it work?
See: https://buildkite.com/wellcomecollection/identity-deployment/builds/1424#0194da4d-c218-44dd-9411-2889837925c1
Identity deployment can proceed.
We should be cautious about deploying to rpod until we have thoroughly tested previous changes.

Fix for subshell hiding sourced env vars
